version: '3.8'

services:
  frontend:
    image: usamaumar465/updated-blog-frontend:latest
    container_name: updated-blog-frontend
    ports:
      - "80:80"   # Adjust if your frontend runs on a different port
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  backend:
    image: usamaumar465/updated-blog-backend:latest
    container_name: updated-blog-backend
    ports:
      - "5000:5000"   # Adjust if your backend runs on a different port
    restart: unless-stopped
    environment:
      - NODE_ENV=production
